### ISSUE TITLE
actualizar las respuestas a las preguntas

### ISSUE THREAD

**Issue by iorch** [mxabierto/sara#40]

**Comment by iorch** [comment]
En espera de que nos manden las respuestas por parte de SAC

**Comment by rodowi** [comment]
Nos contestan el Jueves

**Comment by iorch** [comment]
Enterado, eso mismo me comentó Clark.

**Comment by iorch** [comment]
@rodowi @EduardoClark :¿Ya nos mandaron algo?

**Comment by rodowi** [comment]
sí @iorch -> slack
