### ISSUE TITLE
¿Cómo echamos a andar el proyecto? run.sh? supervisord? foreman?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/sara#47]
Necesitamos correr:

- redis-server
- celery -A tasks worker --loglevel=info
- python ml_classifier.py

**Comment by iorch** [comment]
Habrá que poner un uwsgi, y un supervisor. Para evitar que se caiga el servicio.

**Comment by rodowi** [comment]
ya hay un start.sh en el docker container
