### ISSUE TITLE
Se debe notificar a algún desarrollador de SARA y/o a los de atencion ciudadana en caso de erroes.

### ISSUE THREAD

**Issue by iorch** [mxabierto/sara#58]
En estos momento no tenemos forma de enterarnos si el servicio web deja de funcionar en algún punto. Tenemos que hacer que se nos notifiquen los errores, porque potencialmente podríamos entorpecer el flujo las peticiones de atención ciudadana si por ejemplo, el servicio se cae o empieza a tronar y no nos damos cuenta en varios díás.

**Comment by rodowi** [comment]
podríamos levantar excepciones para que las cache New Relic y nos avisen por correo

http://newrelic.com/

qué opinas @urkonn?

**Comment by urkonn** [comment]
New Relic estaría bien

**Comment by rodowi** [comment]
Ok, entonces ese issue es agregar new relic

**Comment by rodowi** [comment]
Will be fixed by #98 

Lo ves @urkonn

**Comment by urkonn** [comment]
New Relic en el host
