### ISSUE TITLE
Necesitamos rediseñar el valor "proceeds" para indicarle a SAC, por qué no procede algo

### ISSUE THREAD

**Issue by rodowi** [mxabierto/sara#62]
**PUT /petitions/:id**

Ahorita regresa:

```json
{
    "id": 348127,
    "text": "Hey tú cabrón.",
    "agency": 28,
    "proceeds": false
}
```

Dado que nuestro filtro es de malas palabras, deberíamos pasarles el valor "Petición Irrespetuosa"

entonces:

```json
{
    "id": 348127,
    "text": "Hey tú cabrón.",
    "agency": 28,
    "proceeds": "Petición Irrespetuosa"
}
```

y en caso de éxito "proceeds": true

**Comment by chuckcfs** [comment]
pero no entiendo, ¿qué hace ese endpoint? ¿por qué es una petición PUT? ¿esta actualizando algo?

**Comment by iorch** [comment]
@chuckcfs: Actualiza la base de datos (del lado de atención ciudadana), indicando a qué dependencia (agency) debe dirigirse la petición, y admás indica si procede, o no, debido al uso de lenguaje irrespetuoso.

**Comment by chuckcfs** [comment]
@iorch ok pero, ¿esta actualizando una petición?

**Comment by iorch** [comment]
@rodowi, que tal un hash de la siguiente forma:
`"proceeds": {"value": True}`
o 

`"proceeds": {"value": False, "reason":"Lenguaje irrespetuoso"}`

**Comment by rodowi** [comment]
sorry, lo expliqué mal

no es endpoint, es un parámetro que pasamos a SAC y nos regresa un ACK con la copia de los valores

**Comment by rodowi** [comment]
me gusta lo que propone @iorch 

un valor value y reason podría ser

**Comment by iorch** [comment]
@chuckcfs: en principio sí (no lo puedo asegurar porque eso está del lado de atención ciudadana), atención ciudadana recibe un PUT, y ellos actualizan su base de datos con esa nueva información. Ellos ya recibieron antes la petición, nos la mandaron, la analizamos, y nosotros les respondemos con el PUT.

**Comment by chuckcfs** [comment]
ah ok, entonces es fuera del API de SARA, pues si, yo creo que también estaría bien agregar un campo `reason` o algo por el estilo

**Comment by carlosmaya** [comment]
me uno a la propuesta de usar `reason` en la respuesta

**Comment by rodowi** [comment]
la banda de SAC también está de acuerdo.

Por mayoría de votos queda así entonces:

params['proceeds']['value']=false
params['proceeds']['reason']="Petición Irrespetuosa"

**Comment by rodowi** [comment]
:+1: o :-1: ?

**Comment by rodowi** [comment]
https://github.com/mxabierto/sara/wiki/API-del-Sistema-de-Atenci%C3%B3n-Ciudadana

**Comment by chuckcfs** [comment]
pero no estaría mejor sólo agregar un campo separado `reason`??

```json
{
    ...
    "proceeds" : false,
    "reason" : "Petición Irrespetuosa"
}
```

y en caso de que `proceeds` sea `true` no hay `reason`, ¿no?

**Comment by rodowi** [comment]
creo que semánticamente la razón es sobre procede o no

y si está al mismo nivel que proceeds, se entiende que es la razón de la petición en sí, no creen?

**Comment by chuckcfs** [comment]
ya, pero entonces tal vez hacer algo como:

```json
{
    "proceeds" : {
         "value" : true
    }
}
```

y



```json
{
    "proceeds" : {
         "value" : false,
         "reason" : "Petición Irrespetuosa"
    }
}
```

yo digo por mantener uniforme entre respuestas el tipo del campo

**Comment by rodowi** [comment]
:+1: 

así está en el wiki

**Comment by rodowi** [comment]
@chuckcfs es así como dices no? https://github.com/mxabierto/sara/wiki/API-del-Sistema-de-Atenci%C3%B3n-Ciudadana

**Comment by chuckcfs** [comment]
@rodowi si, es lo que a mi se me hace más limpio

**Comment by rodowi** [comment]
¿quién se lo echa?

es nomás meterle mano a este código: https://github.com/mxabierto/sara/blob/master/tasks.py#L50

**Comment by iorch** [comment]
Yo lo tomo
