### ISSUE TITLE
Compilación y Tamaño de la Imagen

### ISSUE THREAD

**Issue by bcessa** [mxabierto/sara#66]
Por el estado actual de la aplicación la imagen docker para correr el servicio de SARA presenta 2 problemas principales:

1.- Es demasiado pesada para ser efectivamente utilizada como un contenedor (__+785MB__)
2.- Es demasiado lento el proceso de compilación, en mayor medida debido a los paquetes:
- __numpy==1.9.2__
- __scikit-learn==0.16.1__
- __scipy==0.15.1__
- __pandas==0.16.0__

Analizando existen varias estrategias ( o combinaciones ) que se pudieran utilizar y necesito feedback para saber por cual irnos:

- Utilizar una imagen base más pequeña, por ejemplo: __[odise/busybox-python](https://registry.hub.docker.com/u/odise/busybox-python/)__; el problema con esta imagen es que no contiene los compiladores y librerías necesarias para hacer el build de los paquetes mencionados, podríamos hacer una con las dependencias completas pero no solucionaría el problema __2__
- Otra opción es incluir en la imagen de runtime una versión _"binaria"_ precompilada del app, python no es muy bueno en este punto :weary: ( Go??? ) pero hay opciones que podríamos explorar, como __[cx-freeze](http://cx-freeze.readthedocs.org/en/latest/)__
- Finalmente podríamos incluir un bundle con las dependencias precompiladas, algo parecido a lo que estamos haciendo con el modelo entrenado previamente e incluirlo como una dependencia externa del app
```sh
pip bundle sara.pybundle sara
pip install sara.pybundle
```

cc/ @rodowi @iorch @urkonn @babasbot @chuckcfs @carlosmaya

**Comment by iorch** [comment]
Me inclino más por la última opción. Incluir un bundle con las dependencias precompiladas.

**Comment by rodowi** [comment]
Bundle precompilado también. Es sano congelar las dependencias y de paso hacemos el boot up más rápido.

**Comment by bcessa** [comment]
Con los ajustes realizados bajo el tamaño de la imagen más de 50% y el tiempo de creación de aprox. 1hr a solo un par de minutos :+1: 

Para optimizar más haría falta dar una revisión en detalle al código y las dependencias/librerías utilizadas
