### ISSUE TITLE
En error, no deberíamos de regresar el stacktrace en producción

### ISSUE THREAD

**Issue by rodowi** [mxabierto/sara#67]

**Comment by urkonn** [comment]
en producción hay que cambiar a
```
debug=False
```

**Comment by iorch** [comment]
Checando la linea dónde está eso
`app.run(host='0.0.0.0', debug=True)`
En producción tampoco deberíámo escuchar todas las IPs, debería estar fija para escuchar sólo a Atención ciudadana. Se puede poner un 
`grep app.run(host='0.0.0.0', debug=True) ml_clasiffier.py | sed 's/True/False/' > tmp; mv tmp ml_clasiffier.py`
en el start.sh, y algo similar con '0.0.0.0', aunque tal vez esta propuesta no entra entre la buenas practicas, jejeje, pero es una forma sencilla de asegurarnos de eso.

**Comment by rodowi** [comment]
mejor 
```python
debug = os.environ['DEBUG'] 
```

**Comment by urkonn** [comment]
#85 arregla esto
