### ISSUE TITLE
Independizar el proceso y dependencias para: Bag Of Words

### ISSUE THREAD

**Issue by bcessa** [mxabierto/sara#71]
En proceso de 'entrenamiento' del modelo de datos es pesado y no es necesario en runtime para el proceso de clasificación de las peticiones, debería manejarse de forma independiente ( con sus dependencias )

**Comment by iorch** [comment]
Los archivos del modelo tambiéns son pesados, vi cuanto pesan en mi sistema:
`>> ls -l bow_ng6_nf9500_ne750*|awk '{sum+=$5} END {print sum/1024/1024}'`
`591.097`

casi 600 MB.

**Comment by rodowi** [comment]
hay que describir mejor el issue en el título
