### ISSUE TITLE
Las ligas de las recomendaciones deben tener el protocolo como prefijo

### ISSUE THREAD

**Issue by rodowi** [mxabierto/sara#81]
Hay algunas recomendaciones que no traen http

**Comment by iorch** [comment]
Puedes poner un ejemplo, en principio eso ya está solucionado con 
https://github.com/mxabierto/sara/commit/2a547f5a88b0e1af5d434c06d4f9be97415d2daa

Todavía no está en master, pero ya está en el último deployment

**Comment by rodowi** [comment]
Si no está en master, no está resuelto

Mandas un PR?

**Comment by iorch** [comment]
OK

**Comment by iorch** [comment]
No sería bueno ya hacer el merge de docker con master? 
El codigo de docker es que que se usa para el deploy, no?

**Comment by rodowi** [comment]
Yo creo, pero hay que validarlo con @urkonn y @bcessa

**Comment by bcessa** [comment]
los deploys que he estado levantando en AWS han sido desde el branch docker desde el inicio; seria solo cuestión de hacer las pruebas contra esa instancia y si ven que todo va bien podríamos ya cerrar ese PR

**Comment by iorch** [comment]
Pues a mi me ha funcionado bien, yo voto por que ya se cierre el PR de docker

**Comment by urkonn** [comment]
@bcessa +1

**Comment by rodowi** [comment]
sí ha estado jalando,
un PR no debe durar tanto tiempo, hay que darle merge ASAP!
